include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

custom_lint:
  rules:
    - riverpod_final_provider
